// frontend-vue/src/AppEndUser.vue
<template>
  <div>
    <div class="bg-primary">
      <div class="container">
        <nav class="navbar navbar-expand navbar-dark bg-primary p-0">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <router-link class="nav-link" to="/">Sản phẩm</router-link>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="javascript:void(0)">Liên hệ</a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    
    <router-view />
  </div>
</template>

<script>
export default {
  name: 'AppEndUser'
}
</script>

<style>

</style>

// frontend-react/src/AppEndUser.js
import React from "react";
import { Switch, Route, Link, withRouter } from "react-router-dom";

import ProductListPage from "features/end_user/product_list/ProductListPage";
import ProductDetailPage from "features/end_user/product_detail/ProductDetailPage";
import OrderProduct from "features/end_user/order/OrderProduct";
import ThankYou from "features/end_user/thank_you/ThankYou";

function AppEndUser() {
  return (
    <>
      <div className="bg-primary">
        <div className="container">
          <nav className="navbar navbar-expand navbar-dark bg-primary p-0">
            <ul className="navbar-nav">
              <li className="nav-item active">
                <Link className="nav-link" to="/">Sản phẩm</Link>
              </li>
              <li className="nav-item">
                <a className="nav-link" href={void(0)}>Liên hệ</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
        
      <Switch>
        
        <Route path="/view-product/:id">
          <ProductDetailPage />
        </Route>

        <Route path="/order-product/:id">
          <OrderProduct />
        </Route>

        <Route path="/thank-you">
          <ThankYou />
        </Route>

        <Route path="/" exact={true}>
          <ProductListPage />
        </Route>
      </Switch>      
    </>
  );
}

export default withRouter(AppEndUser);
